/*
* Generated file
*
* Generated from: yang module name: reservation-provider-impl yang module local name: reservation-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Dec 12 23:06:17 EST 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.reservation_provider.impl;
public class ReservationProviderModuleFactory extends org.opendaylight.controller.config.yang.config.reservation_provider.impl.AbstractReservationProviderModuleFactory {

}
